---
# Source: elasticsearch/templates/data-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch-data-v1
    component: "data"
  name: elasticsearch-data-v1
  namespace: es-cluster

---
# Source: elasticsearch/templates/data-statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch-data-v1
    component: "data"
  name: elasticsearch-data-v1
  namespace: es-cluster
spec:
  serviceName: elasticsearch-data-v1
  replicas: {{conf['es-data-v1']['replicas']}}
  template:
    metadata:
      labels:
        app: elasticsearch-data-v1
        component: "data"
        role: data
    spec:
      serviceAccountName: elasticsearch-data-v1
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "elasticsearch-v1"
                  component: "data"
      initContainers:
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: "sysctl"
        image: "busybox:latest"
        imagePullPolicy: "Always"
        resources:
            {}
            
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: "chown"
        image: "{{conf['es-data-v1']['images'][0]}}"
        imagePullPolicy: "IfNotPresent"
        resources:
            {}
            
        command:
        - /bin/bash
        - -c
        - >
          set -e;
          set -x;
          mkdir -p /usr/share/elasticsearch/log;
          chown elasticsearch:elasticsearch /usr/share/elasticsearch;
          for datadir in $(find /usr/share/elasticsearch -mindepth 1 -maxdepth 1 -not -name ".snapshot"); do
            chown -R elasticsearch:elasticsearch $datadir;
          done;
          chown elasticsearch:elasticsearch /usr/share/elasticsearch/log;
          for logfile in $(find /usr/share/elasticsearch/log -mindepth 1 -maxdepth 1 -not -name ".snapshot"); do
            chown -R elasticsearch:elasticsearch $logfile;
          done
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/share/elasticsearch
          name: es-storage
      containers:
      - name: elasticsearch
        env:
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery-v1
        - name: ES_CLIENT_SVC
          value: elasticsearch-client-v1     
        - name: CLUSTER_NAME
          value: elasticsearch-v1                    
        - name: NODE_MASTER
          value: "false"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms1536m -Xmx1536m  "
        - name: MINIMUM_MASTER_NODES
          value: "2"        
        - name: ES_PATH_DATA
          value: /var/lib/elasticsearch/data
        - name: ES_PATH_LOGS
          value: /usr/share/elasticsearch/log            
{% if conf['es-data-v1']['network-host'] %}
        - name: NETWORK_HOST
          value: {{conf['es-data-v1']['network-host']}}
{% endif %}              
        image: "{{conf['es-data-v1']['images'][0]}}"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 9300
          name: transport

        resources:
            limits:
              cpu: "1"
              memory: 3Gi               
            requests:
              cpu: 25m
              memory: 1536Mi
            
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5          
          
        volumeMounts:
        - mountPath: /var/lib/elasticsearch
          name: es-storage
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - name: config
          mountPath: /pre-stop-hook.sh
          subPath: pre-stop-hook.sh
        - name: config
          mountPath: /post-start-hook.sh
          subPath: post-start-hook.sh
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash","/pre-stop-hook.sh"]
          postStart:
            exec:
              command: ["/bin/bash","/post-start-hook.sh"]
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: config
        configMap:
          name: elasticsearch-v1
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: es-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi  