apiVersion: v1
kind: Service
metadata:
  name: firenoc-services
  namespace: egov
  labels:
    app: firenoc-services
    group: rainmaker
  annotations:
    prometheus.io/path: /firenoc-services/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"    
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: "express"  
  - port: 5005
    targetPort: 5005
    name: "debug"
  selector:
    app: firenoc-services
    group: rainmaker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: firenoc-services
  namespace: egov
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{conf['firenoc-services']['replicas']}}
  template:
    metadata:
      labels:
        app: firenoc-services
        group: rainmaker
    spec:
      initContainers: 
      - name: "firenoc-services-db-migration"
        image: "{{conf["firenoc-services"]["db_migration_image"]}}"
        env: 
        - name: "DB_URL"
          valueFrom: 
            configMapKeyRef: 
              name: egov-config
              key: db-url
        - name: "SCHEMA_TABLE"
          value: "firenoc_services_schema"
        - name: "FLYWAY_USER"
          valueFrom: 
            secretKeyRef: 
              name: db
              key: flyway-username
        - name: "FLYWAY_PASSWORD"
          valueFrom:
            secretKeyRef: 
              name: db
              key: flyway-password
        - name: "FLYWAY_LOCATIONS"
          valueFrom: 
            configMapKeyRef: 
              name: egov-config
              key: flyway-locations
        imagePullPolicy: "IfNotPresent"    
      containers:
      - name: firenoc-services
        image: {{conf['firenoc-services']['images'][0]}}
        ports:
        - containerPort: 8080
          name: "express"
        - containerPort: 5005
          name: "debug"
        # readinessProbe:
        #   httpGet:
        #     path: /firenoc-services/health
        #     port: 8080
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 3
        #   periodSeconds: 30
        #   successThreshold: 1
        #   failureThreshold: 5
        # livenessProbe:
        #   httpGet:
        #     path: /firenoc-services/health
        #     port: 8080
        #   initialDelaySeconds: 120
        #   timeoutSeconds: 3
        #   periodSeconds: 60
        #   successThreshold: 1
        #   failureThreshold: 5
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SERVER_TOMCAT_MAX_THREADS
          value: "{{conf['egov-config']['server-tomcat-max-threads']}}"  
        - name: SERVER_TOMCAT_MAX_CONNECTIONS
          value: "{{conf['egov-config']['server-tomcat-max-connections']}}" 
        - name: SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE
          value: "{{conf['egov-config']['spring-datasource-tomcat-max-active']}}"                         
        - name: FLYWAY_ENABLED
          value: "false"
        - name: EGOV_IDGEN_HOST
          value: "{{conf['egov-service-host']['egov-idgen']}}"
        - name: EGOV_MDMS_HOST
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_USER_HOST
          value: "{{conf['egov-service-host']['egov-user']}}"
        - name: EGOV_LOCATION_HOST
          value: "{{conf['egov-service-host']['egov-location']}}"
        - name: EGOV_WORKFLOW_HOST
          value: "{{conf['egov-service-host']['egov-workflow-v2']}}"         
        - name: EGOV_PROPERTY_HOST
          value: "{{conf['egov-service-host']['pt-services-v2']}}"
        - name: EGOV_LOCALIZATION_HOST
          value: "{{conf['egov-service-host']['egov-localization']}}"
        - name: EGOV_FN_CALCULATOR_HOST
          value: "{{conf['egov-service-host']['firenoc-calculator']}}"                               
        - name: EGOV_MDMS_SEARCH_ENDPOINT
          value: "/egov-mdms-service/v1/_search"
        - name: DB_PORT
          value: "5432"          
        - name: KAFKA_TOPICS_FIRENOC_CREATE
          value: "save-fn-firenoc"
        - name: KAFKA_TOPICS_FIRENOC_UPDATE
          value: "update-fn-firenoc"
        - name: KAFKA_TOPICS_NOTIFICATION_SMS
          value: "egov.core.notification.sms"
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.HashMapDeserializer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: egov-firenoc-services
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        - name: WORKFLOW_CONTEXT_PATH
          value: "{{conf['egov-service-host']['egov-workflow-v2']}}"
        - name: WORKFLOW_TRANSITION_PATH
          value: "egov-workflow-v2/egov-wf/process/_transition"
        - name: KAFKA_BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SERVER_PORT
          value: "8080"
        - name: JAEGER_SERVICE_NAME
          value: firenoc-services
        - name: JAEGER_SAMPLER_TYPE
          value: remote
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
          value: "$(JAEGER_AGENT_HOST):5778"  
        # resources:
        #   requests:
        #     memory: "64Mi"
        #   limits:
        #     memory: "{{ conf['firenoc-services']['memory_limits'] or "512Mi"}}"