apiVersion: v1
kind: Service
metadata:
  name: egov-telemetry-kafka-streams
  namespace: egov
  labels:
    app: egov-telemetry-kafka-streams
    group: core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-telemetry-kafka-streams
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-telemetry-kafka-streams
  namespace: egov
spec:
  replicas: {{conf['egov-telemetry-kafka-streams']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-telemetry-kafka-streams
        group: core
    spec:
      containers:
      - name: egov-telemetry-kafka-streams
        image: {{conf['egov-telemetry-kafka-streams']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: BOOTSTRAP_SERVER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: TELEMETRY_RAW_INPUT
          value: "telemetry-raw-input"
        - name: TELEMETRY_VALIDATED_MESSAGES
          value: "telemetry-validated-messages"
        - name: TELEMETRY_DEDUPED_MESSAGES
          value: "telemetry-deduped-messages"
        - name: TELEMETRY_FINAL_MESSAGES
          value: "telemetry-final-messages"
        - name: STREAM_NAME_TELEMETRY_VALIDATOR
          value: "stream-name-telemetry-validator"
        - name: STREAM_NAME_TELEMETRY_DEDUPLICATOR
          value: "stream-name-telemetry-deduplicator"
        - name: STREAM_NAME_TELEMETRY_UNBUNDLING
          value: "stream-name-telemetry-unbundling"
        - name: STREAM_NAME_TELEMETRY_ENRICHMENT
          value: "stream-name-telemetry-enrichment"
        - name: STREAM_NAME_TELEMETRY_SECOR_FINAL_PUSH
          value: "stream-name-telemetry-secor-final-push"
        - name: STREAM_NAME_TELEMETRY_ELASTICSEARCH_FINAL_PUSH
          value: "stream-name-telemetry-es-final-push"
        - name: DEDUP_STORAGE_TIME
          value: "60"
        - name: SERVER_PORT
          value: "8080"
        - name: JAVA_OPTS
          value: "{{conf['egov-telemetry-kafka-streams']['heap'] or '-Xmx192m -Xms192m'}}"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egov-telemetry-kafka-streams']['memory_limits'] or "256Mi"}}"
