apiVersion: v1
kind: Service
metadata:
  name: hrms-web
  namespace: egov
  labels:
    app: hrms-web
    group: web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hrms-web
    group: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrms-web
  namespace: egov
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{conf['hrms-web']['replicas']}}
  template:
    metadata:
      labels:
        app: hrms-web
        group: web
    spec:
      containers:
      - name: hrms-web
        image: {{conf['hrms-web']['images'][0]}}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /hrms/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "{{ conf['hrms-web']['memory_limits'] or "128Mi"}}"
