apiVersion: v1
kind: Service
metadata:
  name: rainmaker-custom-service
  namespace: egov
  labels:
    app: rainmaker-custom-service
    group: web
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: rainmaker-custom-service
    group: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rainmaker-custom-service
  namespace: egov
spec:
  replicas: {{conf['rainmaker-custom-service']['replicas']}}
  template:
    metadata:
      labels:
        app: rainmaker-custom-service
        group: web
    spec:
      containers:
      - name: rainmaker-custom-service
        image: {{conf['rainmaker-custom-service']['images'][0]}}
        env:
        - name: EGOV_MDMS_HOST
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: DEBUG_MODE
          value: "{{conf['rainmaker-custom-service']['debug-mode']}}"
        - name: NODE_ENV
          value: "{{conf['rainmaker-custom-service']['node-env']}}"
        - name: PT_DEMAND_HOST
          value: "{{conf['egov-service-host']['billing-service']}}"
        - name: DB_HOST
          value: {{conf['rainmaker-custom-service']['db-host']}}
        - name: DB_NAME
          value: {{conf['rainmaker-custom-service']['db-name']}}
        - name: PT_ZERO_ASSESSMENTYEAR
          value: "2013-14"
        - name: PT_ZERO_TENANTS
          value: {{conf['rainmaker-custom-service']['pt-zero-tenants'] or 'pb.zirakpur'}}
{% if conf['rainmaker-custom-service']['egov-bnd-login-url'] %}
        - name: EGOV_BND_LOGIN_URL
          value: {{conf['rainmaker-custom-service']['egov-bnd-login-url']}}
        - name: EGOV_BND_REDIRECT_URL
          value: {{conf['rainmaker-custom-service']['egov-bnd-redirect-url']}}
        - name: EGOV_BND_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: rainmaker-custom-service
              key: egov-bnd-encryption-key
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: rainmaker-custom-service
              key: egov-encryption-key
        - name: ENCRYPTION_IV
          valueFrom:
            secretKeyRef:
              name: rainmaker-custom-service
              key: egov-encryption-iv
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: rainmaker-custom-service
              key: jwt-key
{% endif %}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['rainmaker-custom-service']['memory_limits'] or "64Mi"}}"
